Repository yiisoft/yii-web, pull requests merged in 2019-12, with the labels that each got.

#186 Dispatcher enhancements
  src/Application.php
  src/MiddlewareDispatcher.php
  tests/MiddlewareDispatcherTest.php
Labels: type:enhancement

#192 Fix User::isGuest() return user is not a guest
  src/User/User.php
Labels: type:bug

#157 Trusted hosts network resolver
  composer.json
  src/Middleware/TrustedHostsNetworkResolver.php
  tests/Middleware/TrustedHostsNetworkResolverTest.php
Labels: status:code review

#198 Hotfix/subfolder middleware debug
  src/Exception/BadUriPrefixException.php
  src/Middleware/SubFolder.php
  tests/Middleware/SubFolderTest.php
Labels: status:code review
