Repository yiisoft/yii-web, pull requests merged in 2020-07, with the labels that each got.

#266 Add application tests
  phpunit.xml.dist
  src/Application.php
  src/Event/AfterEmit.php
  src/Event/AfterMiddleware.php
  src/Event/AfterRequest.php
  src/Event/ApplicationShutdown.php
  src/Event/ApplicationStartup.php
  src/Event/BeforeMiddleware.php
  src/Event/BeforeRequest.php
  tests/ApplicationTest.php
  tests/Middleware/RedirectTest.php
  tests/Mock/MockEventDispatcher.php
  tests/Mock/MockMiddleware.php
Labels: status:code review, type:test

#267 added "declare (strict_types = 1);" and classes are set as final
  src/Config/EventConfigurator.php
  src/Data/DataResponse.php
  src/Data/DataResponseFactory.php
  src/Data/DataResponseFactoryInterface.php
  src/Data/DataResponseFormatterInterface.php
  src/Data/Formatter/XmlDataResponseFormatter.php
  src/Data/Middleware/FormatDataResponse.php
  src/Data/Middleware/FormatDataResponseAsHtml.php
  src/Data/Middleware/FormatDataResponseAsJson.php
  src/Data/Middleware/FormatDataResponseAsXml.php
  src/ErrorHandler/ErrorCatcher.php
  src/ErrorHandler/ErrorException.php
  src/ErrorHandler/ErrorHandler.php
  src/ErrorHandler/HtmlRenderer.php
  src/ErrorHandler/JsonRenderer.php
  src/ErrorHandler/PlainTextRenderer.php
  src/ErrorHandler/ThrowableRenderer.php
  src/ErrorHandler/ThrowableRendererInterface.php
  src/ErrorHandler/UserException.php
  src/ErrorHandler/XmlRenderer.php
  src/Exception/BadUriPrefixException.php
  src/Exception/HeadersHaveBeenSentException.php
  src/Flash.php
  src/FlashInterface.php
  src/Info.php
  src/Middleware/BasicNetworkResolver.php
  src/Middleware/Csrf.php
  src/Middleware/HttpCache.php
  src/Middleware/IpFilter.php
  src/Middleware/Redirect.php
  src/Middleware/TagRequest.php
  src/Middleware/TrustedHostsNetworkResolver.php
  src/Middleware/WebActionsCaller.php
  src/MiddlewareDispatcher.php
  src/NotFoundHandler.php
  src/ServerRequestFactory.php
  src/Session/Session.php
  src/Session/SessionException.php
  src/Session/SessionInterface.php
  src/Session/SessionMiddleware.php
  src/User/Event/AfterLogin.php
  src/User/Event/AfterLogout.php
  src/User/Event/BeforeLogin.php
  src/User/Event/BeforeLogout.php
  src/User/GuestIdentity.php
  tests/Session/SessionMiddlewareTest.php
Labels: status:code review

#278 Remove bootstrap.php
  phpunit.xml.dist
  tests/bootstrap.php
Labels: status:code review

#279 Increase coverage with closing #271
  src/ServerRequestFactory.php
  tests/ServerRequestFactoryTest.php
Labels: status:code review, type:test

#276 Cleanup
  src/CookieCollection.php
  src/Data/Formatter/HtmlDataResponseFormatter.php
  src/Data/Formatter/JsonDataResponseFormatter.php
  src/Data/Formatter/XmlDataResponseFormatter.php
  src/ErrorHandler/ErrorCatcher.php
  src/ErrorHandler/HtmlRenderer.php
  src/ErrorHandler/XmlRenderer.php
  src/ErrorHandler/templates/error.php
  src/ErrorHandler/templates/exception.php
  src/ErrorHandler/templates/previousException.php
  src/Middleware/ForceSecureConnection.php
  src/Middleware/HttpCache.php
  src/Middleware/TrustedHostsNetworkResolver.php
  src/NotFoundHandler.php
  src/ServerRequestFactory.php
  src/Session/SessionInterface.php
  src/Session/SessionMiddleware.php
  src/User/User.php
Labels: status:code review

#268 Add user tests
  src/User/User.php
  tests/Mock/MockAccessChecker.php
  tests/Mock/MockIdentity.php
  tests/Mock/MockIdentityRepository.php
  tests/User/UserTest.php
Labels: status:code review, type:test

#282 Fix using event configurator with DI references
  src/Config/EventConfigurator.php
  src/Config/InvalidEventConfigurationFormatException.php
  src/Config/InvalidListenerConfigurationException.php
  tests/Config/EventConfiguratorTest.php
Labels: status:code review

#281 change method name "withAddedRenderer -> withRenderer" and cleanup
  src/ErrorHandler/ErrorCatcher.php
  tests/Middleware/ErrorCatcherTest.php
Labels: status:code review

#286 Make Csrf middleware immutable
  src/Middleware/Csrf.php
  tests/Middleware/CsrfTest.php
Labels: status:code review

#290 Event tests
  tests/EventTest.php
Labels: type:test
