Repository yiisoft/yii-web, pull requests merged in 2020-03, with the labels that each got.

#229 Server request factory tests
  src/ServerRequestFactory.php
  tests/ServerRequestFactoryTest.php
Labels: type:test

#230 Add unique request id
  src/Middleware/TagRequest.php
Labels: status:under discussion

#232 Removed parasitic dependency
  tests/MiddlewareDispatcherTest.php
Labels: status:code review

#231 Removed HeaderHelper with test
  src/ErrorHandler/ErrorCatcher.php
  src/Helper/HeaderHelper.php
  src/Middleware/TrustedHostsNetworkResolver.php
  tests/Helper/HeaderHelperTest.php
Labels: status:code review

#234 Add AfterEmit
  src/Application.php
  src/Event/AfterEmit.php
Labels: status:code review, type:enhancement
