Repository yiisoft/yii-web, pull requests merged in 2020-02, with the labels that each got.

#210 Fix action caller next middleware handling
  src/Middleware/ActionCaller.php
Labels: status:code review, status:under discussion, type:bug

#216 Improve tests
  tests/Emitter/SapiEmitterTest.php
  tests/Middleware/CallbackTest.php
  tests/Middleware/CsrfTest.php
  tests/Middleware/HttpCacheTest.php
  tests/Middleware/IpFilterTest.php
  tests/Middleware/RedirectTest.php
  tests/Middleware/SubFolderTest.php
  tests/MiddlewareDispatcherTest.php
  tests/NotFoundHandlerTest.php
  tests/RateLimiter/CounterTest.php
  tests/RateLimiter/RateLimiterMiddlewareTest.php
  tests/Session/SessionMiddlewareTest.php
Labels: status:code review, type:test

#219 Add stack to MiddlewareDispatcher
  src/MiddlewareDispatcher.php
  tests/MiddlewareDispatcherTest.php
Labels: status:code review

#227 Separate emitter from the Application
  src/Application.php
Labels: type:enhancement
