Repository yiisoft/yii-web, pull requests merged in 2020-08, with the labels that each got.

#295 Add withOnlyRenderer method
  src/ErrorHandler/ErrorCatcher.php
  tests/Middleware/ErrorCatcherTest.php
Labels: status:code review

#296 Allow set return content type
  src/ErrorHandler/ErrorCatcher.php
  tests/Middleware/ErrorCatcherTest.php
Labels: status:code review

#300 fix legacy middleware double pass
  src/MiddlewareDispatcher.php
Labels: pr:request for unit tests, status:code review

#303 Fix error handler
  src/ErrorHandler/ErrorHandler.php
  src/ErrorHandler/HtmlRenderer.php
Labels: status:code review, type:bug

#305 Yiisoft auth fix
  src/User/UserAuth.php
  tests/Mock/MockIdentityRepository.php
  tests/User/UserAuthTest.php
Labels: status:code review
