Repository yiisoft/yii-web, pull requests merged in 2020-05, with the labels that each got.

#235 AutoLoginMiddleware #218
  src/User/AuthenticationKeyInterface.php
  src/User/AutoLogin.php
  src/User/AutoLoginIdentityInterface.php
  src/User/AutoLoginMiddleware.php
  src/User/Event/AfterLogin.php
  src/User/Event/AfterLogout.php
  src/User/Event/BeforeLogin.php
  src/User/Event/BeforeLogout.php
  src/User/GuestIdentity.php
  src/User/User.php
  tests/User/AutoLoginIdentity.php
  tests/User/AutoLoginMiddlewareTest.php
  tests/User/AutoLoginTest.php
Labels: status:code review

#253 Use returned response object with added header in AutologinMiddleware
  src/User/AutoLoginMiddleware.php
Labels: type:bug

#217 Custom templates for HtmlRenderer
  config/params.php
  config/web.php
  src/ErrorHandler/HtmlRenderer.php
  tests/ErrorHandler/HtmlRendererTest.php
Labels: type:enhancement

#256 Fix emitter with not readable stream
  src/SapiEmitter.php
  tests/Emitter/SapiEmitterTest.php
  tests/Emitter/Support/HTTPFunctions.php
  tests/Emitter/Support/HTTPFunctionsTest.php
  tests/Emitter/Support/NotReadableStream.php
  tests/Emitter/Support/httpFunctionMocks.php
Labels: status:code review

#255 Unit tests patch
  tests/Data/Formatter/XmlDataResponseFormatterTest.php
  tests/ErrorHandler/ErrorHandlerTest.php
Labels: status:code review, type:test
