Repository yiisoft/yii-web, pull requests merged in 2020-01, with the labels that each got.

#200 Clean up session
  src/Session/Session.php
Labels: status:code review

#185 HeaderHelper::getParameters() fix #184
  src/Helper/HeaderHelper.php
  tests/Helper/HeaderHelperTest.php
Labels: status:under development

#199 Porting http cache
  composer.json
  src/Middleware/HttpCache.php
  tests/Middleware/HttpCacheTest.php
Labels: status:code review, type:enhancement

#208 Use http Status
  src/Emitter/SapiEmitter.php
  src/ErrorHandler/ErrorCatcher.php
  src/ErrorHandler/ErrorHandler.php
  src/Middleware/Csrf.php
  src/Middleware/HttpCache.php
  src/Middleware/IpFilter.php
  src/Middleware/Redirect.php
  src/NotFoundHandler.php
  tests/Middleware/RedirectTest.php
Labels: status:code review

#204 Rate limiter implementation(gcra)
  src/RateLimiter/Counter.php
  src/RateLimiter/CounterInterface.php
  src/RateLimiter/CounterState.php
  src/RateLimiter/RateLimiterMiddleware.php
  tests/RateLimiter/CounterTest.php
  tests/RateLimiter/FakeCounter.php
  tests/RateLimiter/RateLimiterMiddlewareTest.php
Labels: status:code review, status:ready for merge
