Repository yiisoft/yii-web, pull requests merged in 2020-04, with the labels that each got.

#233 Add response formatters
  composer.json
  src/Data/DataResponse.php
  src/Data/DataResponseFactory.php
  src/Data/DataResponseFactoryInterface.php
  src/Data/DataResponseFormatterInterface.php
  src/Data/Formatter/HtmlDataResponseFormatter.php
  src/Data/Formatter/JsonDataResponseFormatter.php
  src/Data/Formatter/XmlDataResponseFormatter.php
  src/Data/Middleware/FormatDataResponse.php
  src/Data/Middleware/FormatDataResponseAsHtml.php
  src/Data/Middleware/FormatDataResponseAsJson.php
  src/Data/Middleware/FormatDataResponseAsXml.php
  tests/Data/DataResponseTest.php
  tests/Data/Formatter/HtmlDataResponseFormatterTest.php
  tests/Data/Formatter/JsonDataResponseFormatterTest.php
  tests/Data/Formatter/XmlDataResponseFormatterTest.php
  tests/Data/Middleware/FormatDataResponseTest.php
Labels: status:code review

#238 Add event manager
  composer.json
  src/Config/EventConfigurator.php
  tests/Config/Event.php
  tests/Config/EventConfiguratorTest.php
  tests/Data/Middleware/FormatDataResponseTest.php
Labels: status:code review

#239 Update EventConfigurator
  src/Config/EventConfigurator.php
  tests/Config/Event.php
  tests/Config/EventConfiguratorTest.php
Labels: status:code review

#240 Fix session
  src/Session/SessionMiddleware.php
Labels: status:to be verified, type:bug

#243 Add strict encoding
  src/ErrorHandler/JsonRenderer.php
Labels: status:code review

#241 Add meta
  .phpstorm.meta.php/Cookie.php
  .phpstorm.meta.php/DataResponseFactoryInterface.php
Labels: status:code review

#242 Refactored a little bit
  src/Config/EventConfigurator.php
  src/Data/Formatter/XmlDataResponseFormatter.php
Labels: status:code review

#246 Remove ratelimiter
  src/RateLimiter/Counter.php
  src/RateLimiter/CounterInterface.php
  src/RateLimiter/CounterState.php
  src/RateLimiter/RateLimiterMiddleware.php
  tests/RateLimiter/CounterTest.php
  tests/RateLimiter/FakeCounter.php
  tests/RateLimiter/RateLimiterMiddlewareTest.php
Labels: status:code review

#244 Refactor Cookie, add CookieCollection
  .phpstorm.meta.php/Cookie.php
  src/Cookie.php
  src/CookieCollection.php
  src/Session/SessionMiddleware.php
  tests/CookieCollectionTest.php
  tests/CookieTest.php
Labels: status:code review

#249 Use 5 bits per character for sid, to have valid cookie value
  src/Session/Session.php
Labels: type:bug
